export const GET_PROPERTIES = 'GET_PROPERTIES';
export const GET_PROPERTY = 'GET_PROPERTY';
export const GET_QUERY_PROPERTY = 'GET_QUERY_PROPERTY';

export const GET_FORM_QUERY = 'GET_FORM_QUERY';
export const POST_QUERY = 'POST_QUERY';
export const GET_QUERY_PROPERTIES = 'GET_QUERY_PROPERTIES';
